site_name: Archipelago Documentation
site_url: https://docs.archipelago.nyc
site_description: Project documentation for Archipelago.
site_author: The Digital Services Team at Metropolitan New York Library Council (METRO)
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
