site_name: Archipelago Documentation
site_url: https://docs.archipelago.nyc
site_description: Project documentation for Archipelago.
site_author: The Digital Services Team at Metropolitan New York Library Council
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/esmero
      name: Archipelago Commons + esmero
    - icon: fontawesome/brands/slack
      link: https://archipelagocommons.slack.com
      name: Archipelago Commons Slack Channe
    - icon: material/forum-outline
      link: https://groups.google.com/g/archipelago-commons
      name: Archipelago Commons Google Group
